name: docs-additional

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install latex
      run: sudo apt install -y latexmk texlive-latex-extra texlive-science

    - name: Give permission to execute
      run: chmod u+x *.sh

    - name: Compile exams
      run: make extra
